version: 2.1

executors:
  my:
    docker:
      - image: circleci/buildpack-deps:bionic

jobs:
  build:
    executor: my
    steps:
      # apt prepare
      - run: sudo apt update --fix-missing
      - run: sudo apt install -y nodejs npm node-gyp nodejs-dev libssl1.0-dev # clang gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      # verify
      - run: node --version
      - run: npm --version
      # make cache folder (if missing) and take ownership
      - run: sudo mkdir -p /usr/local/n
      - run: sudo chown -R $(whoami) /usr/local/n
      # take ownership of node install destination folders
      - run: sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/include /usr/local/share
      # upgrade node + add yarn
      - run: npm i -g n
      - run: n 16
      - run: npm i -g yarn
      - run: node --version
      - run: npm --version
      - run: yarn --version
      # test here to reuse all of above (same job)
      - checkout
      - run: yarn
      - run: yarn test
workflows:
  version: 2
  test:
    jobs:
      - build
